; Name: Arpit Kumar Mohanty
; Registration Number: 2341013237
; Section: 23412G1
; Lab 2 Objective - 1   //MULTIPLICATION OF TWO 16 BIT NUMBER WITHOUT USING MUL INSTRUCTION IN DIRECT ADDRESSING MODE

MOV AX, 0000H
MOV DS, AX
MOV SI, 4000H
MOV CX, [SI]
INC SI
INC SI
MOV BX, [SI]
MOV DX, 0000H  
MOV AX, 0000H

L2: ADD AX, [SI]
JNC L1
INC DX

L1: DEC CL
JNZ L2
INC SI
INC SI
MOV [SI], AX
INC SI
INC SI
MOV [SI], DX
HLT